travis:
  secure:
    BINSTAR_TOKEN: kFnDtMvtQZWvcE/1DUyAK0IoDM72FOtz0J/bx82JQJHOXUTlbaoxhpSbpYOKsBZpZ2yhlQ4PJFIE6Yg5tcZa+iB2K/idaC9YwhK7KsroYA7PiNwplaZYMzsBxRAxK911dHCgA8VOwerkL3ZfOEgmv4jXX0ZQ2vLE0AshgFjJH/CjixWbX7XUltTCOF0NMzM73CRPAtwmJ/ZWoCLqezLA1b57Ma62vQWpHgab7cEN2SPbhckhP8/RlsD0NF95Pdkt32x526gzDtjbCASjQz/CNlxNB5bLi1t78hoLRQyLhgDcGPaIbzOVeFyXV2jSppkqR+yY57cP1FLXowZidXX8Fk6k4Fk4Bi9kIaccPTb1508O93vEKOMflMTM0NLNbcugJdC6bebfOBJTrggVrobMPEu6nSXpWaMgYaNbeYZZ6hF0smU7g4z9QHPTXLjzyeW8xFAG4mfIb7ipACOLZLcRZXy2dMPWr8VVKMPNlQzAGB/pZUi/jzBpZzVl7Zivnqbsz8qcwALFUJBo+HIYw1xitTZP3ldKl9jNhFG+wGfTuyJb/hw3wennd1zupVQx1DwNi8bGJCg6qWfltjjes4g+blCTMsJcv5AKboVZ6PnGfk7dSzWPgXe01rL5Qwg6QYsFlls+mIShRVQWeRO+rRuA8BtE3nC7g6R8jNKR8r8rsa0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
